import { CompressedData } from './types.js';

export class CodeGenerator {
  static generateVanillaJS(compressedData: CompressedData): string {
    return `/*
 * This code was generated by Human Replay (https://einenlum.github.io/human-replay/)
 */
const replayText = (element, values) => {
    element.textContent = '';
    const printingStart = new Date();

    let localInterval = setInterval(() => {
        const timePassed = new Date() - printingStart;

        const value = values.shift();

        if (!value) {
            clearInterval(localInterval);

            return;
        }

        if (value.t > timePassed) {
            values.unshift(value);

            return;
        }

        switch (value.op) {
            case 'a':
                element.textContent = element.textContent + value.v;
                break;
            case 'd':
                element.textContent = element.textContent.slice(0, -1);
                break;
            default:
                element.textContent = value.v;
        }
    }, 20);

    return localInterval;
}

const values = ${JSON.stringify(compressedData)};

// const myElement = document.getElementById('your-element-id');
replayText(myElement, values);
`;
  }
}